### ISSUE TITLE
Release 0.11 checklist

### ISSUE THREAD

**Issue by Mixih** [coala/coala-bears#1679]
Stage 0:
- [x] split the release branch [completed 4/26]
- [ ] bump master version to 0.12
- [ ] update bears to use new coala dev version

Stage 1:
- [ ] ship release candidate to pypi
- [ ] test release candidate
- [ ] prepare release notes [Delegated to @meetmangukiya]

Stage 2:
- [ ] ship release 0.11 (manually verify everything is in order before shipping)

Stage 3 (post release):
- [ ] twitter
- [ ] blog?

Please append critical backports to this issue before release

**Comment by Mixih** [comment]
xref https://github.com/coala/coala/issues/4144
