### ISSUE TITLE
Release 0.10.3 checklist

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala-bears#1702]
Stage 0:
- [ ] merge the bug fixes to 0.10 branch
- [ ] bump version to 0.10.3

Stage 1:
- [ ] prepare release notes

Stage 2:
- [ ] ship release 0.11 (manually verify everything is in order before shipping)

Stage 3 (post release):
- [ ] twitter
- [ ] blog?

Please append critical backports to this issue before release
